name: Sonar Cloud Code Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full clone for proper analysis

      - name: Cache SonarScanner CLI
        uses: actions/cache@v3
        id: sonar-scanner-cache
        with:
          # The sonar-scanner CLI is cached in the ~/.sonar/cache directory.
          path: ~/.sonar/cache
          # Use a key that reflects the OS and the scanner version.
          key: ${{ runner.os }}-sonar-scanner-cli-6.2.1.4610-Linux-X64
          restore-keys: |
            ${{ runner.os }}-sonar-scanner-cli-

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
